<a href="https://colab.research.google.com/github/afham123/Deep-Learning-Project/blob/main/Keras_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import genfromtxt
%matplotlib inline

In [4]:
from google.colab import files
uploaded = files.upload()

Saving bank_note_data.txt to bank_note_data.txt


In [5]:
data = genfromtxt('bank_note_data.txt', delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
label=data[:,4]

In [7]:
features=data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [38]:
label.shape

(1372,)

In [10]:
X=features
y=label

In [40]:
print(X_train.shape)
print(y_train.shape)

(919, 4)
(919,)


In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.33)

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scaler=MinMaxScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [44]:
from keras.models import Sequential
from keras.layers import Dense

In [45]:
model=Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [46]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy',])

In [47]:
y_train.shape

(919,)

In [48]:
model.fit(X_train,y_train,epochs=250,verbose=2,validation_data=(X_test,y_test))

Epoch 1/250
29/29 - 1s - loss: 0.6928 - accuracy: 0.5495 - val_loss: 0.6794 - val_accuracy: 0.5673
Epoch 2/250
29/29 - 0s - loss: 0.6837 - accuracy: 0.5495 - val_loss: 0.6709 - val_accuracy: 0.5673
Epoch 3/250
29/29 - 0s - loss: 0.6750 - accuracy: 0.5495 - val_loss: 0.6613 - val_accuracy: 0.5673
Epoch 4/250
29/29 - 0s - loss: 0.6655 - accuracy: 0.5495 - val_loss: 0.6504 - val_accuracy: 0.5673
Epoch 5/250
29/29 - 0s - loss: 0.6515 - accuracy: 0.5495 - val_loss: 0.6345 - val_accuracy: 0.5673
Epoch 6/250
29/29 - 0s - loss: 0.6344 - accuracy: 0.5495 - val_loss: 0.6168 - val_accuracy: 0.5673
Epoch 7/250
29/29 - 0s - loss: 0.6166 - accuracy: 0.5495 - val_loss: 0.6005 - val_accuracy: 0.5695
Epoch 8/250
29/29 - 0s - loss: 0.5997 - accuracy: 0.6202 - val_loss: 0.5844 - val_accuracy: 0.6600
Epoch 9/250
29/29 - 0s - loss: 0.5817 - accuracy: 0.6681 - val_loss: 0.5674 - val_accuracy: 0.7307
Epoch 10/250
29/29 - 0s - loss: 0.5628 - accuracy: 0.7606 - val_loss: 0.5510 - val_accuracy: 0.7704
Epoch 11/

In [49]:
loss_df=pd.DataFrame(model.history.history)
loss_df.head()

loss  accuracy  val_loss  val_accuracy
0  0.692752   0.54951  0.679408      0.567329
1  0.683739   0.54951  0.670908      0.567329
2  0.675033   0.54951  0.661289      0.567329
3  0.665468   0.54951  0.650401      0.567329
4  0.651538   0.54951  0.634505      0.567329

In [50]:
prediction=model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [52]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [53]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       257
         1.0       1.00      1.00      1.00       196

    accuracy                           1.00       453
   macro avg       1.00      1.00      1.00       453
weighted avg       1.00      1.00      1.00       453



In [54]:
print(confusion_matrix(y_test,prediction))

[[257   0]
 [  0 196]]


In [55]:
print(accuracy_score(y_test,prediction))

1.0


In [63]:
model.save('My_model.h5')

In [66]:
from keras.models import load_model
my_model=load_model('My_model.h5')

In [ ]:
print(my_model.predict_classes(X_test))